import type { AudioAssetDto, SpeakerDto, SyllableMark } from './types';

/**
 * 方言示例音频元数据（种子数据）。
 * 配套 WAV 由 apps/api/src/seeds/generate-wavs.ts 程序化生成，
 * 无需携带二进制文件即可在新环境复现。
 *
 * 覆盖：粤语(广州) / 西南官话(成都) / 吴语(苏州) / 闽南语(厦门) / 客家话(梅州) / 湘语(长沙)
 */

export const SAMPLE_SPEAKERS: Array<Omit<SpeakerDto, 'version' | 'updatedAt' | 'deletedAt' | 'deviceId' | 'consentSignedAt'> & { id: string }> = [
  {
    id: 'spk-cantonese-01',
    code: 'YUE-GZ-001',
    name: '陈阿婆（示例发音人）',
    gender: 'F',
    birthYear: 1958,
    dialect: '粤语-广州话',
    region: '广东省广州市荔湾区',
    consentStatus: 'granted',
    consentScope: 'course',
    consentHash: 'sha256:demo-consent-v1-cantonese01',
    notes: '示例数据：已签署研究+课程用途授权',
  },
  {
    id: 'spk-southwestern-01',
    code: 'SWG-CD-002',
    name: '王师傅（示例发音人）',
    gender: 'M',
    birthYear: 1972,
    dialect: '西南官话-成渝片-成都话',
    region: '四川省成都市锦江区',
    consentStatus: 'granted',
    consentScope: 'research',
    consentHash: 'sha256:demo-consent-v1-chengdu02',
    notes: '仅授权学术研究，课程发布需再次确认',
  },
  {
    id: 'spk-wu-01',
    code: 'WUU-SZ-003',
    name: '周阿姨（示例发音人）',
    gender: 'F',
    birthYear: 1965,
    dialect: '吴语-太湖片-苏州话',
    region: '江苏省苏州市姑苏区',
    consentStatus: 'granted',
    consentScope: 'public',
    consentHash: 'sha256:demo-consent-v1-suzhou03',
    notes: '同意公开示范',
  },
  {
    id: 'spk-minnan-01',
    code: 'NAN-XM-004',
    name: '林先生（示例发音人）',
    gender: 'M',
    birthYear: 1980,
    dialect: '闽南语-泉漳片-厦门话',
    region: '福建省厦门市思明区',
    consentStatus: 'granted',
    consentScope: 'course',
    consentHash: 'sha256:demo-consent-v1-xiamen04',
    notes: null,
  },
  {
    id: 'spk-hakka-01',
    code: 'HAK-MZ-005',
    name: '钟姐（示例发音人）',
    gender: 'F',
    birthYear: 1990,
    dialect: '客家语-粤台片-梅州话',
    region: '广东省梅州市梅江区',
    consentStatus: 'pending',
    consentScope: null,
    consentHash: null,
    notes: '待补签纸质授权书；音频默认 restricted',
  },
  {
    id: 'spk-xiang-01',
    code: 'HSN-CS-006',
    name: '刘老师（示例发音人）',
    gender: 'M',
    birthYear: 1961,
    dialect: '湘语-长益片-长沙话',
    region: '湖南省长沙市天心区',
    consentStatus: 'revoked',
    consentScope: null,
    consentHash: 'sha256:demo-consent-v1-changsha06',
    notes: '授权已撤回：该发音人的素材禁止再分发，仅可留存归档',
  },
];

interface SampleAudioSeed {
  asset: Omit<AudioAssetDto, 'version' | 'updatedAt' | 'deletedAt' | 'deviceId' | 'filePath' | 'waveformPeaks' | 'recordedAt'>;
  /** 生成演示 WAV 用的基频 Hz（不同方言给不同音高轮廓） */
  baseFreq: number;
  syllables: SyllableMark[];
}

export const SAMPLE_AUDIO: SampleAudioSeed[] = [
  {
    baseFreq: 220,
    syllables: [
      { start: 0.12, end: 0.42, label: 'nei˨˧', gloss: '你' },
      { start: 0.46, end: 0.82, label: 'hou˧˥', gloss: '好' },
      { start: 0.9, end: 1.45, label: 'maː˧', gloss: '吗' },
    ],
    asset: {
      id: 'aud-yue-hello',
      title: '广州话：你好吗？',
      speakerId: 'spk-cantonese-01',
      ownerId: 'usr-investigator-01',
      dialect: '粤语-广州话',
      durationSec: 1.6,
      sampleRate: 16000,
      channels: 1,
      mime: 'audio/wav',
      transcript: '你好吗？',
      translation: '你好吗？',
      ipa: 'nei˨˧ hou˧˥ maː˧',
      syllables: [],
      status: 'published',
      sensitive: false,
      keyVersion: null,
    },
  },
  {
    baseFreq: 174,
    syllables: [
      { start: 0.1, end: 0.5, label: 'ŋo˨˩', gloss: '我' },
      { start: 0.55, end: 1.0, label: 'sɿ˥˧', gloss: '是' },
      { start: 1.05, end: 1.6, label: 'tsʰən˨˩tu˨˩', gloss: '成都' },
      { start: 1.65, end: 2.0, label: 'nən˨˩˧', gloss: '人' },
    ],
    asset: {
      id: 'aud-swg-chengdu',
      title: '成都话：我是成都人',
      speakerId: 'spk-southwestern-01',
      ownerId: 'usr-investigator-01',
      dialect: '西南官话-成渝片-成都话',
      durationSec: 2.1,
      sampleRate: 16000,
      channels: 1,
      mime: 'audio/wav',
      transcript: '我是成都人',
      translation: '我是成都人',
      ipa: 'ŋo˨˩ sɿ˥˧ tsʰən˨˩tu˨˩ nən˨˩˧',
      syllables: [],
      status: 'annotated',
      sensitive: false,
      keyVersion: null,
    },
  },
  {
    baseFreq: 246,
    syllables: [
      { start: 0.1, end: 0.55, label: 'noŋ˨˧', gloss: '侬' },
      { start: 0.6, end: 1.0, label: 'tsʰi˥˩', gloss: '吃' },
      { start: 1.05, end: 1.5, label: 've˨˧˩', gloss: '饭' },
      { start: 1.55, end: 1.9, label: 'tsi˥˨', gloss: '了' },
      { start: 1.95, end: 2.3, label: 'a˧', gloss: '吗' },
    ],
    asset: {
      id: 'aud-wu-suzhou',
      title: '苏州话：侬吃饭了啊？',
      speakerId: 'spk-wu-01',
      ownerId: 'usr-investigator-01',
      dialect: '吴语-太湖片-苏州话',
      durationSec: 2.4,
      sampleRate: 16000,
      channels: 1,
      mime: 'audio/wav',
      transcript: '侬吃饭了啊？',
      translation: '你吃饭了吗？',
      ipa: 'noŋ˨˧ tsʰi˥˩ ve˨˧˩ tsi˥˨ a˧',
      syllables: [],
      status: 'published',
      sensitive: false,
      keyVersion: null,
    },
  },
  {
    baseFreq: 196,
    syllables: [
      { start: 0.1, end: 0.45, label: 'ka˧˨', gloss: '今' },
      { start: 0.5, end: 0.85, label: 'a˥˥', gloss: '哑' },
      { start: 0.9, end: 1.25, label: 'lit˩', gloss: '日' },
      { start: 1.3, end: 1.7, label: 'sĩ˧˧', gloss: '天' },
      { start: 1.75, end: 2.1, label: 'kʰi˥˩', gloss: '气' },
      { start: 2.15, end: 2.6, label: 'ho˥˧', gloss: '好' },
    ],
    asset: {
      id: 'aud-nan-xiamen',
      title: '厦门话：今仔日天气好',
      speakerId: 'spk-minnan-01',
      ownerId: 'usr-investigator-01',
      dialect: '闽南语-泉漳片-厦门话',
      durationSec: 2.7,
      sampleRate: 16000,
      channels: 1,
      mime: 'audio/wav',
      transcript: '今仔日天气好',
      translation: '今天天气好',
      ipa: 'ka˧˨ a˥˥ lit˩ sĩ˧˧ kʰi˥˩ ho˥˧',
      syllables: [],
      status: 'published',
      sensitive: false,
      keyVersion: null,
    },
  },
  {
    baseFreq: 233,
    syllables: [
      { start: 0.1, end: 0.5, label: 'ŋai˩', gloss: '我' },
      { start: 0.55, end: 1.0, label: 'oi˥˧', gloss: '爱' },
      { start: 1.05, end: 1.5, label: 'sit˩', gloss: '食' },
      { start: 1.55, end: 2.1, label: 'pak̚˩ tʰɔŋ˩', gloss: '白糖（糕）' },
    ],
    asset: {
      id: 'aud-hak-meizhou',
      title: '梅州客家话：我爱吃白糖糕（授权待签 · 受限）',
      speakerId: 'spk-hakka-01',
      ownerId: 'usr-investigator-01',
      dialect: '客家语-粤台片-梅州话',
      durationSec: 2.2,
      sampleRate: 16000,
      channels: 1,
      mime: 'audio/wav',
      transcript: '我爱食白糖糕',
      translation: '我想吃白糖糕',
      ipa: 'ŋai˩ oi˥˧ sit˩ pak̚˩ tʰɔŋ˩ kau˧',
      syllables: [],
      status: 'restricted',
      sensitive: true,
      keyVersion: 1,
    },
  },
  {
    baseFreq: 185,
    syllables: [
      { start: 0.1, end: 0.6, label: 'so˧˩', gloss: '锁' },
      { start: 0.65, end: 1.1, label: 'tei˧˩', gloss: '在' },
      { start: 1.15, end: 1.5, label: 'na˧˧', gloss: '哪' },
      { start: 1.55, end: 1.9, label: 'li˧˩', gloss: '里' },
    ],
    asset: {
      id: 'aud-hsn-changsha-locked',
      title: '长沙话：锁在哪里？（授权已撤回 · 禁止分发）',
      speakerId: 'spk-xiang-01',
      ownerId: 'usr-investigator-01',
      dialect: '湘语-长益片-长沙话',
      durationSec: 2.0,
      sampleRate: 16000,
      channels: 1,
      mime: 'audio/wav',
      transcript: '锁在哪里？',
      translation: '钥匙在哪里？',
      ipa: 'so˧˩ tei˧˩ na˧˧ li˧˩',
      syllables: [],
      status: 'restricted',
      sensitive: true,
      keyVersion: 1,
    },
  },
];
